#!/bin/bash

CONFIGS=(
	"5 50 1.5% 14 400 0.1"
	"5 50 1.0% 14 400 0.1"
	"5 50 1.5% 14 600 0.1"
	"5 50 0.5% 14 400 0.1"
	"5 50 1.0% 13 400 0.1"
)

ROOT_DIR="/global/cfs/projectdirs/atlas/jashley/mjolnir/beta/code"
WORKING_DIR="${ROOT_DIR}/temp-results"
cd ${WORKING_DIR}
echo "Changed directory to ${WORKING_DIR}"

for i in "${!CONFIGS[@]}"
do
	echo "Reading configuration ${i}"

	read -r k t s d n b <<< "${CONFIGS[$i]}"

	# Format hyperparameters for easy stringing
	s_safe=${s//./-}; s_safe=${s_safe//\%/}
	b_safe=${b//./-}
	KFCV_TAG="${t}_${s_safe}_${d}_${n}_${b_safe}"

	PROCESS_LOG="${KFCV_TAG}_process.log"

	# Collect and plot scores
	echo "Processing BDT performance for ${t} micron sensor data"
        echo "with ${k} folds, MinNodeSize=${s}, MaxDepth=${d},"
	echo "NTrees=${n}, AdaBoost beta=${b}"

	python ${ROOT_DIR}/plot_roccs.py \
	-k ${k} -t ${t} -s ${s} -d ${d} -n ${n} -b ${b} \
	| tee ${PROCESS_LOG}
	date >> ${PROCESS_LOG}
	echo "Folds Thickness MinNodeSize MaxDepth NTrees beta" >> ${PROCESS_LOG}
	echo "${CONFIGS[$i]}" >> ${PROCESS_LOG}
done

echo "Changing directory back to"
cd -
