#!/bin/bash

CONFIGS=(
	"5 50 0.5% 12 200 0.1"
	"5 50 0.5% 14 200 0.1"
	"5 50 0.5% 13 200 0.1"
	"5 50 0.5% 13 400 0.1"
	"5 50 1.0% 12 400 0.1"
	"5 50 1.0% 10 400 0.1"
	"5 50 1.5% 14 200 0.1"
)

WORKING_DIR="/global/cfs/projectdirs/atlas/jashley/mjolnir/beta/code"
cd ${WORKING_DIR}
echo "Changed directory to ${WORKING_DIR}"

for i in "${!CONFIGS[@]}"
do
	echo "Reading configuration ${i}"

	read -r k t s d n b <<< "${CONFIGS[$i]}"

	# Format hyperparameters for easy stringing
	s_safe=${s//./-}; s_safe=${s_safe//\%/}
	b_safe=${b//./-}
	KFCV_TAG="${t}_${s_safe}_${d}_${n}_${b_safe}"

	# Run k-fold CrossValidation
	echo "Initiating BDT training for ${t} micron sensor data"
	echo "with ${k} folds, MinNodeSize=${s}, MaxDepth=${d},"
	echo "NTrees=${n}, AdaBoost beta=${b}"

	TRAINING_LOG="${KFCV_TAG}_v2_training.log"
	python cross-validation.py \
	-k ${k} -t ${t} -s ${s} -d ${d} -n ${n} -b ${b} \
	| tee ${TRAINING_LOG}
	date >> ${TRAINING_LOG}
	echo "Folds Thickness MinNodeSize MaxDepth NTrees beta" >> ${TRAINING_LOG}
	echo "${CONFIGS[$i]}" >> ${TRAINING_LOG}
	echo "=== Training completed, log saved to ${TRAINING_LOG} ==="

	# Evaluate CrossValidation performance
	echo "Initiating BDT evaluation for ${t} micron sensor data"
	echo "with ${k} folds, MinNodeSize=${s}, MaxDepth=${d},"
	echo "NTrees=${n}, AdaBoost beta=${b}"

	EVALUATION_LOG="${KFCV_TAG}_v2_evaluation.log"
	python evaluate_tmva_bdt.py \
	-k ${k} -t ${t} -s ${s} -d ${d} -n ${n} -b ${b} \
	| tee ${EVALUATION_LOG}
	date >> ${EVALUATION_LOG}
	echo "Folds Thickness MinNodeSize MaxDepth NTrees beta" >> ${EVALUATION_LOG}
	echo "${CONFIGS[$i]}" >> ${EVALUATION_LOG}
	echo "=== Evaluation completed, log saved to ${EVALUATION_LOG} ==="

	# Collect and plot scores
	echo "Processing BDT performance for ${t} micron sensor data"
        echo "with ${k} folds, MinNodeSize=${s}, MaxDepth=${d},"
	echo "NTrees=${n}, AdaBoost beta=${b}"

	PROCESS_LOG="${KFCV_TAG}_v2_process.log"
	python get_CV_scores.py \
	-k ${k} -t ${t} -s ${s} -d ${d} -n ${n} -b ${b}
	python plot_roccs.py \
	-k ${k} -t ${t} -s ${s} -d ${d} -n ${n} -b ${b} \
	| tee ${PROCESS_LOG}
	date >> ${PROCESS_LOG}
	echo "Folds Thickness MinNodeSize MaxDepth NTrees beta" >> ${PROCESS_LOG}
	echo "${CONFIGS[$i]}" >> ${PROCESS_LOG}
	
	# Move output files to intermediary results subdirectory
	echo "Contents of current directory:"
	ls
	echo "Contents of temp-results directory:"
	ls temp-results
	echo "Moving results to temp-results..."
	mv ${KFCV_TAG}_* temp-results/

	echo "Renaming per-fold ROOT files and moving..."
	echo "(e.g., 'BDT_fold1.root' -> '${KFCV_TAG}_v2_fold1.root')"
	for i in {1..5}
	do
		mv BDT_fold${i}.root temp-results/${KFCV_TAG}_v2_fold${i}.root
	done
	
	echo "Post-move contents of working directory:"
	ls
	echo "Post-move contents of temp-results:"
	ls temp-results
done

echo "Changing directory back to"
cd -
