// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : CrossValidation::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.30/06       [400902]
Creator        : jashley
Date           : Tue Apr  7 12:18:57 2026
Host           : Linux runner-z8jooa6tn-project-190437-concurrent-0-p18ptnml 6.6.13-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 20 18:03:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /global/cfs/cdirs/atlas/jashley/mjolnir/beta/code
Training events: 17483
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
EncapsulatedMethodName: "BDT" []
EncapsulatedMethodTypeName: "BDT" []
NumFolds: "5" [Number of folds to generate]
OutputEnsembling: "None" [Combines output from contained methods. If None, no combination is performed. (default None)]
SplitExpr: "[fold]" [The expression used to assign events to folds]
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 32
Cluster_ArrivalTime           Cluster_ArrivalTime           Cluster_ArrivalTime           Cluster_ArrivalTime                                             'F'    [-0.449798971415,0.44998139143]
Cluster_EnergyDeposited       Cluster_EnergyDeposited       Cluster_EnergyDeposited       Cluster_EnergyDeposited                                         'F'    [3.68849441656e-06,0.00773312104866]
Incident_Angle                Incident_Angle                Incident_Angle                Incident_Angle                                                  'F'    [0.434898227453,2.71486949921]
Cluster_Size_x                Cluster_Size_x                Cluster_Size_x                Cluster_Size_x                                                  'F'    [1,375]
Cluster_Size_y                Cluster_Size_y                Cluster_Size_y                Cluster_Size_y                                                  'F'    [1,3553]
Cluster_Size_tot              Cluster_Size_tot              Cluster_Size_tot              Cluster_Size_tot                                                'F'    [1,3326]
Cluster_x                     Cluster_x                     Cluster_x                     Cluster_x                                                       'F'    [-31.1060085297,31.1044139862]
Cluster_y                     Cluster_y                     Cluster_y                     Cluster_y                                                       'F'    [-31.1091976166,31.1091976166]
Cluster_z                     Cluster_z                     Cluster_z                     Cluster_z                                                       'F'    [-66.3625030518,64.9625015259]
Cluster_RMS_x                 Cluster_RMS_x                 Cluster_RMS_x                 Cluster_RMS_x                                                   'F'    [2.56146577158e-05,84181.8828125]
Cluster_RMS_y                 Cluster_RMS_y                 Cluster_RMS_y                 Cluster_RMS_y                                                   'F'    [0.108925573528,1001824.25]
Cluster_Skew_x                Cluster_Skew_x                Cluster_Skew_x                Cluster_Skew_x                                                  'F'    [-1.93091881275,1.88485610485]
Cluster_Skew_y                Cluster_Skew_y                Cluster_Skew_y                Cluster_Skew_y                                                  'F'    [-1.56349599361,1.70994353294]
Cluster_AspectRatio           Cluster_AspectRatio           Cluster_AspectRatio           Cluster_AspectRatio                                             'F'    [0,2442953]
PixelHits_EnergyDeposited_0   PixelHits_EnergyDeposited_0   PixelHits_EnergyDeposited_0   PixelHits_EnergyDeposited_0                                     'F'    [759.5,26208]
PixelHits_EnergyDeposited_1   PixelHits_EnergyDeposited_1   PixelHits_EnergyDeposited_1   PixelHits_EnergyDeposited_1                                     'F'    [0,26208]
PixelHits_EnergyDeposited_2   PixelHits_EnergyDeposited_2   PixelHits_EnergyDeposited_2   PixelHits_EnergyDeposited_2                                     'F'    [0,26208]
PixelHits_EnergyDeposited_3   PixelHits_EnergyDeposited_3   PixelHits_EnergyDeposited_3   PixelHits_EnergyDeposited_3                                     'F'    [0,26208]
PixelHits_EnergyDeposited_4   PixelHits_EnergyDeposited_4   PixelHits_EnergyDeposited_4   PixelHits_EnergyDeposited_4                                     'F'    [0,26208]
PixelHits_EnergyDeposited_5   PixelHits_EnergyDeposited_5   PixelHits_EnergyDeposited_5   PixelHits_EnergyDeposited_5                                     'F'    [0,26208]
PixelHits_EnergyDeposited_6   PixelHits_EnergyDeposited_6   PixelHits_EnergyDeposited_6   PixelHits_EnergyDeposited_6                                     'F'    [0,19958.5]
PixelHits_EnergyDeposited_7   PixelHits_EnergyDeposited_7   PixelHits_EnergyDeposited_7   PixelHits_EnergyDeposited_7                                     'F'    [0,11575]
PixelHits_EnergyDeposited_8   PixelHits_EnergyDeposited_8   PixelHits_EnergyDeposited_8   PixelHits_EnergyDeposited_8                                     'F'    [0,8814.5]
PixelHits_ArrivalTime_0       PixelHits_ArrivalTime_0       PixelHits_ArrivalTime_0       PixelHits_ArrivalTime_0                                         'F'    [-0.352703213692,0.797424197197]
PixelHits_ArrivalTime_1       PixelHits_ArrivalTime_1       PixelHits_ArrivalTime_1       PixelHits_ArrivalTime_1                                         'F'    [-0.380745053291,0.806654989719]
PixelHits_ArrivalTime_2       PixelHits_ArrivalTime_2       PixelHits_ArrivalTime_2       PixelHits_ArrivalTime_2                                         'F'    [-0.352843999863,0.818193554878]
PixelHits_ArrivalTime_3       PixelHits_ArrivalTime_3       PixelHits_ArrivalTime_3       PixelHits_ArrivalTime_3                                         'F'    [-0.354178607464,0.850059747696]
PixelHits_ArrivalTime_4       PixelHits_ArrivalTime_4       PixelHits_ArrivalTime_4       PixelHits_ArrivalTime_4                                         'F'    [-0.32837921381,0.812524855137]
PixelHits_ArrivalTime_5       PixelHits_ArrivalTime_5       PixelHits_ArrivalTime_5       PixelHits_ArrivalTime_5                                         'F'    [-0.366690337658,0.766377866268]
PixelHits_ArrivalTime_6       PixelHits_ArrivalTime_6       PixelHits_ArrivalTime_6       PixelHits_ArrivalTime_6                                         'F'    [-0.344565927982,0.740161120892]
PixelHits_ArrivalTime_7       PixelHits_ArrivalTime_7       PixelHits_ArrivalTime_7       PixelHits_ArrivalTime_7                                         'F'    [-0.380850195885,0.788814127445]
PixelHits_ArrivalTime_8       PixelHits_ArrivalTime_8       PixelHits_ArrivalTime_8       PixelHits_ArrivalTime_8                                         'F'    [-0.323289513588,0.715506672859]
NSpec 1
fold                          fold                          fold                          I                                                               'F'    [0,4]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 32 )
   {
      // the training input variables
      const char* inputVars[] = { "Cluster_ArrivalTime", "Cluster_EnergyDeposited", "Incident_Angle", "Cluster_Size_x", "Cluster_Size_y", "Cluster_Size_tot", "Cluster_x", "Cluster_y", "Cluster_z", "Cluster_RMS_x", "Cluster_RMS_y", "Cluster_Skew_x", "Cluster_Skew_y", "Cluster_AspectRatio", "PixelHits_EnergyDeposited_0", "PixelHits_EnergyDeposited_1", "PixelHits_EnergyDeposited_2", "PixelHits_EnergyDeposited_3", "PixelHits_EnergyDeposited_4", "PixelHits_EnergyDeposited_5", "PixelHits_EnergyDeposited_6", "PixelHits_EnergyDeposited_7", "PixelHits_EnergyDeposited_8", "PixelHits_ArrivalTime_0", "PixelHits_ArrivalTime_1", "PixelHits_ArrivalTime_2", "PixelHits_ArrivalTime_3", "PixelHits_ArrivalTime_4", "PixelHits_ArrivalTime_5", "PixelHits_ArrivalTime_6", "PixelHits_ArrivalTime_7", "PixelHits_ArrivalTime_8" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;
      fVmin[27] = 0;
      fVmax[27] = 0;
      fVmin[28] = 0;
      fVmax[28] = 0;
      fVmin[29] = 0;
      fVmax[29] = 0;
      fVmin[30] = 0;
      fVmax[30] = 0;
      fVmin[31] = 0;
      fVmax[31] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';
      fType[29] = 'F';
      fType[30] = 'F';
      fType[31] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[32];
   double fVmax[32];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[32];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
